/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A game message */
        Message: {
            player: string;
            text: string;
        };
        /** @description An item that players can collect */
        Item: {
            name: string;
        };
        /** @description A monster */
        Monster: {
            name?: string;
            stars: number;
        };
        /** @description Public player information */
        Player: {
            name: string;
            ready: boolean;
            coins?: number;
            num_items?: number;
            health?: number;
        };
        /** @description Private player information (only visible to that player) */
        PlayerHand: {
            items: components["schemas"]["Item"][];
        };
        /** @description High-level game state used while browsing */
        GameStatus: {
            /** @example 3 */
            num_players: number;
            /**
             * @example in_lobby
             * @enum {string}
             */
            status: "in_lobby" | "in_game" | "ended";
        };
        /** @description Current board state */
        BoardState: {
            deck: {
                /** @description Number of cards remaining in deck */
                size: number;
                /** @description Star value of top card */
                top_card_stars: number;
            };
            shop: {
                /** @description Number of items available in shop */
                size: number;
            };
            /** @description Only present during combat phase */
            monsters?: {
                visible?: components["schemas"]["Monster"][];
                flipped?: {
                    stars?: number;
                }[];
            };
        };
        /**
         * @description Actions players can take on their turn
         * @enum {string}
         */
        PlayerActionChoice: "COINS" | "SHOP" | "FSF" | "END";
        /** @description SERVER → CLIENT: Response when creating a game */
        CreateGameResponse: {
            /** @example game_123 */
            game_id: string;
        };
        /** @description CLIENT → SERVER: Request to join a game */
        JoinGameRequest: {
            /** @example Bob */
            player_name: string;
        };
        /** @description Used to actually join game after connecting to server */
        JoinRequest: {
            game_id: string;
            player_name: string;
        };
        /** @description Used in lobby to let others know they're ready to start */
        LobbyReadyRequest: {
            ready: boolean;
        };
        /** @description Called by owning client to start game when all are ready */
        StartGameRequest: Record<string, never>;
        /** @description Called by client to end their turn during the game */
        EndTurnRequest: Record<string, never>;
        /** @description Called by client send a message */
        ChatRequest: {
            text: string;
        };
        /** @description Used to do game actions like using items or fsf */
        ActionRequest: {
            choice: components["schemas"]["PlayerActionChoice"];
        };
        /** @description Acknowledgement if action was successful or the result */
        ActionAcknowledge: {
            successful: boolean;
        };
        /** @description Initializes game for a new join */
        InitResponse: {
            game_name: string;
            game_owner: string;
            max_players: number;
            players: components["schemas"]["Player"][];
            messages: components["schemas"]["Message"][];
            status: string;
            active_player?: string;
        };
        /** @description event to move out of lobby phase */
        StartGameEvent: {
            first_player: string;
        };
        /** @description Event to update players information */
        PlayersEvent: {
            players: components["schemas"]["Player"][];
        };
        /** @description Event when a chat is sent to everyone */
        ChatEvent: {
            message: components["schemas"]["Message"];
        };
        /** @description Event to tell clients that the turn changed */
        ChangeTurnEvent: {
            new_active: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
