# generated by datamodel-codegen:
#   filename:  api_schema.yaml
#   timestamp: 2025-12-12T01:33:12+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, conint


class Message(BaseModel):
    player: str
    text: str


class Item(BaseModel):
    name: str


class Monster(BaseModel):
    name: Optional[str] = None
    stars: conint(ge=1, le=3)


class Player(BaseModel):
    name: str
    ready: bool
    coins: Optional[int] = None
    num_items: Optional[int] = None
    health: Optional[int] = None


class PlayerHand(BaseModel):
    items: List[Item]


class Status(Enum):
    in_lobby = 'in_lobby'
    in_game = 'in_game'
    ended = 'ended'


class GameStatus(BaseModel):
    num_players: conint(ge=0) = Field(..., examples=[3])
    status: Status = Field(..., examples=['in_lobby'])


class Deck(BaseModel):
    size: int = Field(..., description='Number of cards remaining in deck')
    top_card_stars: int = Field(..., description='Star value of top card')


class Shop(BaseModel):
    size: int = Field(..., description='Number of items available in shop')


class FlippedItem(BaseModel):
    stars: Optional[int] = None


class Monsters(BaseModel):
    visible: Optional[List[Monster]] = None
    flipped: Optional[List[FlippedItem]] = None


class BoardState(BaseModel):
    deck: Deck
    shop: Shop
    monsters: Optional[Monsters] = Field(
        None, description='Only present during combat phase'
    )


class PlayerActionChoice(Enum):
    COINS = 'COINS'
    SHOP = 'SHOP'
    FSF = 'FSF'
    END = 'END'


class CreateGameResponse(BaseModel):
    game_id: str = Field(..., examples=['game_123'])


class JoinGameRequest(BaseModel):
    player_name: str = Field(..., examples=['Bob'])


class JoinRequest(BaseModel):
    game_id: str
    player_name: str


class LobbyReadyRequest(BaseModel):
    ready: bool


class StartGameRequest(BaseModel):
    pass


class EndTurnRequest(BaseModel):
    pass


class ChatRequest(BaseModel):
    text: str


class ActionRequest(BaseModel):
    choice: PlayerActionChoice


class ActionAcknowledge(BaseModel):
    successful: bool


class InitResponse(BaseModel):
    game_name: str
    game_owner: str
    max_players: int
    players: List[Player]
    messages: List[Message]
    status: str
    active_player: Optional[str] = None


class StartGameEvent(BaseModel):
    first_player: str


class PlayersEvent(BaseModel):
    players: List[Player]


class ChatEvent(BaseModel):
    message: Message


class ChangeTurnEvent(BaseModel):
    new_active: str
